// <auto-generated />
namespace ThisIsFantasy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class _450 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_450));
        
        string IMigrationMetadata.Id
        {
            get { return "201910301449467_450"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
