// <auto-generated />
namespace ThisIsFantasy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class next50 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(next50));
        
        string IMigrationMetadata.Id
        {
            get { return "201910301440573_next50"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
