namespace ThisIsFantasy.Migrations
{
    using System;
    using System.Data.Entity.Migrations;

    public partial class seedPlayerStats : DbMigration
    {
        public override void Up()
        {
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Ainsley Maitland-Niles', 7792, 'Maitland-Niles A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Alexandre Lacazette', 7797, 'Lacazette A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Bernd Leno', 3174, 'Leno B.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Bukayo Saka', 99813, 'Saka B.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Calum Chambers', 7787, 'Chambers C.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Dani Ceballos', 68, 'Ceballos D.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('David Luiz', 7805, 'Luiz D.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Emile Smith-Rowe', 85570, 'Smith-Rowe E.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Emiliano Martínez', 3141, 'Martínez E.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Folarin Balogun', 131040, 'Balogun F.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Granit Xhaka', 3477, 'Xhaka G.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Héctor Bellerín', 7783, 'Bellerin H.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Joe Willock', 7798, 'Willock J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Kieran Tierney', 15615, 'Tierney K.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Konstantinos Mavropanos', 7789, 'Mavropanos K.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Lucas Torreira', 2260, 'Torreira L.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Martinelli', 61450, ', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Matt Macey', 7779, 'Macey M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Mattéo Guendouzi', 600, 'Guendouzi M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Mesut Özil', 3180, 'Ozil M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Nicolas Pépé', 8412, 'Pepe N.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Pierre-Emerick Aubameyang', 7801, 'Aubameyang P.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Reiss Nelson', 7799, 'Nelson R.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Rob Holding', 7784, 'Holding R.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Robbie Burton', 131039, 'Burton R.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Sead Kolašinac', 7786, 'Kolasinac S.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Shkodran Mustafi', 7785, 'Mustafi S.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Sokratis Papastathopoulos', 137, 'Papastathopoulos S.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Tolaji Bola', 131038, 'Bola T.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Unai Emery', 11616, 'Emery U.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Ahmed El Mohamady', 3753, 'El Mohamady A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Anwar El Ghazi', 8411, 'El Ghazi A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Björn Engels', 15986, 'Engels B.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Cameron Archer', 128242, 'Archer C.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Conor Hourihane', 3900, 'Hourihane C.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Dean Smith', 11339, 'Smith D.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Douglas Luiz', 33525, 'Luiz D.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Ezri Konsa', 6317, 'Konsa E.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Frédéric Guilbert', 8324, 'Guilbert F.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Henri Lansbury', 3898, 'Lansbury H.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Jack Grealish', 3895, 'Grealish J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Jacob Ramsey', 111437, 'Ramsey J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('James Chester', 3889, 'Chester J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Jed Steer', 3883, 'Steer J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('John McGinn', 34646, 'McGinn J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Jonathan Kodjia', 3913, 'Kodjia J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Jota Peleteiro', 4124, 'Peleteiro J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Keinan Davis', 3896, 'Davis K.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Kortney Hause', 4082, 'Hause K.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Lovre Kalini?', 3547, 'Kalinic L.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Marvelous Nakamba', 8885, 'Nakamba M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Matt Targett', 3962, 'Targett M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Neil Taylor', 3890, 'Taylor N.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Ørjan Nyland', 6843, 'Nyland O.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Tom Heaton', 8035, 'Heaton T.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Trezeguet', 3759, 'Trezeguet, 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Tyrone Mings', 8235, 'Mings T.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Wesley', 8891, 'Wesley, 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Andreas Christensen', 3455, 'Christensen A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Antonio Rüdiger', 3177, 'Rudiger A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Azpilicueta', 3191, 'Azpilicueta, 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Billy Gilmour', 126289, 'Gilmour B.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Callum Hudson-Odoi', 7816, 'Hudson-Odoi C.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Christian Pulisic', 145, 'Pulisic C.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Emerson', 7809, 'Emerson, 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Faustino Anjorin', 131119, 'Anjorin F.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Fikayo Tomori', 11528, 'Tomori F.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Frank Lampard', 25598, 'Lampard F.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Ian Maatsen', 131120, 'Maatsen I.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Jamie Cumming', 101077, 'Cumming J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Jorginho', 2094, 'Jorginho, 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Kepa Arrizabalaga', 3189, 'Arrizabalaga K.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Kurt Zouma', 7948, 'Zouma K.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Marc Guéhi', 118489, 'Guehi M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Marco van Ginkel', 7450, 'van Ginkel M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Marcos Alonso', 3195, 'Alonso M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Mason Mount', 7599, 'Mount M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Mateo Kova?i?', 65, 'Kovacic M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Michy Batshuayi', 3664, 'Batshuayi M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('N'Golo Kanté', 3367, 'Kante N.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Olivier Giroud', 3371, 'Giroud O.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Pedro', 7818, 'Pedro, 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Reece James', 56628, 'James R.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Ross Barkley', 7817, 'Barkley R.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Ruben Loftus-Cheek', 8159, 'Loftus-Cheek R.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Tammy Abraham', 7985, 'Abraham T.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Willian', 3230, 'Willian, 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Willy Caballero', 3203, 'Caballero W.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Alex Iwobi', 3392, 'Iwobi A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('André Gomes', 3251, 'Gomes A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Baye Oumar Niasse', 3630, 'Niasse O.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Beni Baningime', 7844, 'Baningime B.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Bernard', 16476, 'Bernard, 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Cenk Tosun', 7854, 'Tosun C.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Cuco Martina', 7830, 'Martina C.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Djibril Sidibé', 3362, 'Sidibe D.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Dominic Calvert-Lewin', 7839, 'Calvert-Lewin D.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Fabian Delph', 7886, 'Delph F.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Gylfi Þór Sigurðsson', 7842, 'Sigurdsson G.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Jean-Philippe Gbamin', 6623, 'Gbamin J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Jonas Lössl', 3449, 'Lossl J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Jordan Pickford', 3309, 'Pickford J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Leighton Baines', 7824, 'Baines L.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Lucas Digne', 3359, 'Digne L.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Maarten Stekelenburg', 7822, 'Stekelenburg M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Marco Silva', 11579, 'Silva M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Mason Holgate', 7826, 'Holgate M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Michael Keane', 7829, 'Keane M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Moise Kean', 2171, 'Kean M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Morgan Schneiderlin', 7840, 'Schneiderlin M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Richarlison', 8133, 'Richarlison, 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Séamus Coleman', 7836, 'Coleman S.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Theo Walcott', 7855, 'Walcott T.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Tom Davies', 7837, 'Davies T.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Yerry Mina', 3728, 'Mina Y.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Adam Lallana', 3318, 'Lallana A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Adam Lewis', 131116, 'Lewis A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Adrián', 8197, 'Adrian, 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Alex Oxlade-Chamberlain', 3323, 'Oxlade-Chamberlain A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Alisson', 1795, 'Alisson, 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Andrew Lonergan', 4133, 'Lonergan A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Andrew Robertson', 7868, 'Robertson A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Caoimhin Kelleher', 102046, 'Kelleher C.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Curtis Jones', 7873, 'Jones C.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Dejan Lovren', 7859, 'Lovren D.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Divock Origi', 3663, 'Origi D.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Fabinho', 8749, 'Fabinho, 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Georginio Wijnaldum', 7871, 'Wijnaldum G.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Harvey Elliot', 92053, 'Elliot H.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Herbie Kane', 76753, 'Kane H.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('James Milner', 7861, 'Milner J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Joe Gomez', 7862, 'Gomez J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Joël Matip', 7865, 'Matip J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Jordan Henderson', 3320, 'Henderson J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Jürgen Klopp', 9344, 'Klopp J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Ki-Jana Hoever', 102044, 'Jana Hoever K.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Leighton Clarkson', 131118, 'Clarkson L.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Luis Longstaff', 131117, 'Longstaff L.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Mohamed Salah', 3754, 'Salah M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Naby Keïta', 9547, 'Keita N.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Nathaniel Clyne', 7863, 'Clyne N.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Pedro Chirivella', 7397, 'Chirivella P.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Rhian Brewster', 7877, 'Brewster R.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Roberto Firmino', 3233, 'Firmino R.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Sadio Mané', 3626, 'Mane S.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Sepp van den Berg', 7720, 'van den Berg S.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Trent Alexander-Arnold', 7867, 'Alexander-Arnold T.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Virgil van Dijk', 7869, 'van Dijk V.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Xherdan Shaqiri', 7955, 'Shaqiri X.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Adrián Bernabé', 92051, 'Bernabe A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Alpha Richard Dionkou', 131036, 'Richard Dionkou A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Angeliño', 7646, 'Angelino, 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Arteta', 11619, 'Arteta, 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Aymeric Laporte', 7884, 'Laporte A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Benjamin Mendy', 7882, 'Mendy B.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Bernardo Silva', 3254, 'Silva B.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Brian Kidd', 133312, 'Kidd B.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Claudio Bravo', 7879, 'Bravo C.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Daniel Grimshaw', 102441, 'Grimshaw D.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('David Silva', 3196, 'Silva D.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Ederson', 3222, 'Ederson, 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Eric', 101345, 'Eric, 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Fernandinho', 3227, 'Fernandinho, 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Gabriel Jesus', 3236, 'Jesus G.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Ilkay Gündogan', 3182, 'Gundogan I.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('João Cancelo', 2000, 'Cancelo J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('John Stones', 3313, 'Stones J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Kevin De Bruyne', 3654, 'De Bruyne K.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Kyle Walker', 3311, 'Walker K.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Leroy Sané', 3184, 'Sane L.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Nicolás Otamendi', 3205, 'Otamendi N.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Oleksandr Zinchenko', 7889, 'Zinchenko O.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Pep Guardiola', 11603, 'Guardiola P.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Phil Foden', 7888, 'Foden P.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Raheem Sterling', 3329, 'Sterling R.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Riyad Mahrez', 8069, 'Mahrez R.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Rodri', 3199, 'Rodri, 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Scott Carson', 4172, 'Carson S.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Sergio Agüero', 7891, 'Aguero S.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Taylor Harwood-Bellis', 131035, 'Harwood-Bellis T.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Aaron Wan-Bissaka', 8158, 'Wan-Bissaka A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Andreas Pereira', 33153, 'Pereira A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Angel Gomes', 7910, 'Gomes A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Anthony Martial', 3372, 'Martial A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Ashley Young', 3317, 'Young A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Axel Tuanzebe', 3894, 'Tuanzebe A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Brandon Williams', 131126, 'Williams B.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Daniel James', 7974, 'James D.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('David De Gea', 3188, 'De Gea D.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Diogo Dalot', 15905, 'Dalot D.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Eric Bailly', 7901, 'Bailly E.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Fred', 3232, 'Fred, 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Harry Maguire', 3326, 'Maguire H.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('James Garner', 101076, 'Garner J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Jesse Lingard', 3325, 'Lingard J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Lee Grant', 7942, 'Grant L.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Luke Shaw', 7898, 'Shaw L.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Marcos Rojo', 3206, 'Rojo M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Marcus Rashford', 3331, 'Rashford M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Mason Greenwood', 101075, 'Greenwood M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Mata', 7909, 'Mata, 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Nemanja Mati?', 3438, 'Matic N.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Ole Gunnar Solskjær', 38106, 'Gunnar Solskjær O.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Paul Pogba', 3366, 'Pogba P.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Phil Jones', 7897, 'Jones P.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Scott McTominay', 7905, 'McTominay S.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Sergio Romero', 3202, 'Romero S.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Tahith Chong', 98483, 'Chong T.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Timothy Fosu-Mensah', 8148, 'Fosu-Mensah T.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Victor Nilsson-Lindelöf', 3492, 'Lindelof V.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Allan Saint-Maximin', 8446, 'Saint-Maximin A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Andy Carroll', 8219, 'Carroll A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Christian Atsu', 7932, 'Atsu C.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Ciaran Clark', 7923, 'Clark C.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('DeAndre Yedlin', 7924, 'Yedlin D.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Dwight Gayle', 7937, 'Gayle D.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Emil Krafth', 1868, 'Krafth E.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Fabian Schär', 88, 'Schar F.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Federico Fernández', 7968, 'Fernandez F.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Florian Lejeune', 7925, 'Lejeune F.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Henri Saivet', 3634, 'Saivet H.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Isaac Hayden', 7922, 'Hayden I.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Jack Colback', 11775, 'Colback J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Jamal Lascelles', 7919, 'Lascelles J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Javier Manquillo', 7928, 'Manquillo J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Jetro Willems', 6708, 'Willems J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Joelinton', 10653, 'Joelinton, 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Jonjo Shelvey', 7929, 'Shelvey J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Karl Darlow', 7913, 'Darlow K.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Ki Sungyueng', 3342, 'Sungyueng K.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Martin Dúbravka', 7914, 'Dubravka M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Matt Ritchie', 7930, 'Ritchie M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Matthew Longstaff', 128310, 'Longstaff M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Miguel Almirón', 76861, 'Almiron M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Paul Dummett', 7917, 'Dummett P.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Rob Elliot', 7912, 'Elliot R.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Sean Longstaff', 4955, 'Longstaff S.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Steve Bruce', 11421, 'Bruce S.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Yoshinori Mut?', 6627, 'Muto Y.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Adam Idah', 125561, 'Idah A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Akin Famewo', 5605, 'Famewo A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Alexander Tettey', 3989, 'Tettey A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Archie Mair', 131964, 'Mair A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Ben Godfrey', 5487, 'Godfrey B.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Christoph Zimmermann', 3985, 'Zimmermann C.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Daniel Farke', 11323, 'Farke D.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Dennis Srbeny', 4001, 'Srbeny D.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Emiliano Buendía', 31941, 'Buendia E.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Grant Hanley', 3986, 'Hanley G.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Ibrahim Amadou', 8394, 'Amadou I.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Jamal Lewis', 3998, 'Lewis J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Josip Drmi?', 3480, 'Drmic J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Kenny McLean', 34494, 'McLean K.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Marco Stiepermann', 3997, 'Stiepermann M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Mario Vran?i?', 3993, 'Vrancic M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Max Aarons', 80765, 'Aarons M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Michael McGovern', 3980, 'McGovern M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Moritz Leitner', 4002, 'Leitner M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Onel Hernández', 4000, 'Hernandez O.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Patrick Roberts', 16076, 'Roberts P.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Philip Heise', 9960, 'Heise P.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Ralf Fährmann', 6489, 'Fahrmann R.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Sam Byram', 8203, 'Byram S.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Teemu Pukki', 24121, 'Pukki T.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Tim Krul', 8258, 'Krul T.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Timm Klose', 3982, 'Klose T.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Todd Cantwell', 11601, 'Cantwell T.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Tom Trybull', 3996, 'Trybull T.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Alfie Whiteman', 7992, 'Whiteman A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Ben Davies', 7994, 'Davies B.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Brandon Austin', 133229, 'Austin B.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Christian Eriksen', 3459, 'Eriksen C.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Danny Rose', 3319, 'Rose D.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Davinson Sánchez', 3733, 'Sanchez D.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Dele Alli', 3324, 'Alli D.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Eric Dier', 3314, 'Dier E.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Erik Lamela', 8005, 'Lamela E.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Giovani Lo Celso', 3216, 'Lo Celso G.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Harry Kane', 8004, 'Kane H.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Harry Winks', 7999, 'Winks H.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Hugo Lloris', 3355, 'Lloris H.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Jan Vertonghen', 3646, 'Vertonghen J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Japhet Tanganga', 131037, 'Tanganga J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Juan Foyth', 7996, 'Foyth J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Kyle Walker-Peters', 7995, 'Walker-Peters K.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Lucas Moura', 8003, 'Moura L.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Mauricio Pochettino', 11609, 'Pochettino M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Michel Vorm', 7991, 'Vorm M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Moussa Sissoko', 8001, 'Sissoko M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Oliver Skipp', 96974, 'Skipp O.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Paulo Gazzaniga', 7993, 'Gazzaniga P.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Ryan Sessegnon', 3959, 'Sessegnon R.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Serge Aurier', 7997, 'Aurier S.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Son Heungmin', 3343, 'Son Heung-Min, 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Tanguy Ndombèlé', 8469, 'Ndombele T.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Toby Alderweireld', 3648, 'Alderweireld T.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Troy Parrot', 131041, 'Parrot T.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Victor Wanyama', 8000, 'Wanyama V.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Aaron Lennon', 8052, 'Lennon A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Adam Legzdins', 8036, 'Legzdins A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Adam Phillips', 6296, 'Phillips A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Ashley Barnes', 8054, 'Barnes A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Ashley Westwood', 8050, 'Westwood A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Bailey Peacock-Farrell', 4131, 'Peacock-Farrell B.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Ben Gibson', 4207, 'Gibson B.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Benjamin Mee', 8038, 'Mee B.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Charlie Taylor', 8043, 'Taylor C.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Chris Wood', 8057, 'Wood C.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Danny Drinkwater', 7814, 'Drinkwater D.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Dwight McNeil', 11623, 'McNeil D.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Erik Pieters', 7944, 'Pieters E.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Jack Cork', 8051, 'Cork J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('James Tarkowski', 3316, 'Tarkowski J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Jay Rodriguez', 8032, 'Rodriguez J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Jeff Hendrick', 8049, 'Hendrick J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Joe Hart', 3307, 'Hart J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Joel Senior', 124825, 'Senior J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Jóhann Berg Guðmundsson', 3839, 'Gudmundsson J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Kevin Long', 8041, 'Long K.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Lewis Richardson', 128313, 'Richardson L.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Mat?j Vydra', 4195, 'Vydra M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Matthew Lowton', 8040, 'Lowton M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Nick Pope', 3310, 'Pope N.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Phil Bardsley', 8044, 'Bardsley P.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Robbie Brady', 8042, 'Brady R.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Ryan Cooney', 5217, 'Cooney R.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Sean Dyche', 11584, 'Dyche S.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Ayoze Pérez', 7936, 'Perez A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Bartosz Kapustka', 9491, 'Kapustka B.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Ben Chilwell', 8065, 'Chilwell B.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Brendan Rodgers', 15624, 'Rodger B.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Ça?lar Söyüncü', 9475, 'Soyuncu C.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Christian Fuchs', 8064, 'Fuchs C.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Daniel Amartey', 8066, 'Amartey D.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Danny Ward', 7857, 'Ward D.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Demarai Gray', 8072, 'Gray D.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Dennis Praet', 2259, 'Praet D.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Eldin Jakupovic', 8060, 'Jakupovic E.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Filip Benkovi?', 23122, 'Benkovic F.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Hamza Choudhury', 8075, 'Choudhury H.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Harvey Barnes', 8076, 'Barnes H.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('James Justin', 5613, 'Justin J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('James Maddison', 3992, 'Maddison J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Jamie Vardy', 3330, 'Vardy J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Jonny Evans', 8014, 'Evans J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Kasper Schmeichel', 3448, 'Schmeichel K.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Kelechi Iheanacho', 3400, 'Iheanacho K.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Marc Albrighton', 8071, 'Albrighton M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Matty James', 8070, 'James M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Nampalys Mendy', 8441, 'Mendy N.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Ricardo Pereira', 10182, 'Pereira R.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Wes Morgan', 8061, 'Morgan W.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Wilfred Ndidi', 3383, 'Ndidi W.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Youri Tielemans', 3658, 'Tielemans Y.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Alex McCarthy', 8080, 'McCarthy A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Angus Gunn', 3981, 'Gunn A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Cédric', 3244, 'Cedric, 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Che Adams', 4119, 'Adams C.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Dan Nlundulu', 128564, 'Nlundulu D.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Danny Ings', 7875, 'Ings D.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Harry Lewis', 35254, 'Lewis H.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Jack Stephens', 8085, 'Stephens J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('James Ward-Prowse', 8088, 'Ward-Prowse J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Jan Bednarek', 8086, 'Bednarek J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Jannik Vestergaard', 6671, 'Vestegaard J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Kevin Danso', 6655, 'Danso K.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Maya Yoshida', 8082, 'Yoshida M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Michael Obafemi', 8102, 'Obafemi M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Moussa Djénepo', 9240, 'Djenepo M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Nathan Redmond', 8092, 'Redmond N.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Oriol Romeu', 8091, 'Romeu O.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Pierre Emile Højbjerg', 8093, 'Hojbjerg P.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Ralph Hasenhüttl', 43924, 'Hasenhuttl R.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Ryan Bertrand', 8083, 'Bertrand R.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Sam McQueen', 8095, 'McQueen S.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Shane Long', 8098, 'Long S.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Sofiane Boufal', 3706, 'Boufal S.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Stuart Armstrong', 15614, 'Armstrong S.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Yan Valery', 99799, 'Valery Y.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Abdoulaye Doucouré', 8119, 'Doucoure A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Adam Masina', 1865, 'Masina A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Adrian Mariappa', 8114, 'Mariappa A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Andre Gray', 8134, 'Gray A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Ben Foster', 8009, 'Foster B.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Christian Kabasele', 8111, 'Kabasele C.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Craig Cathcart', 8107, 'Catchart C.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Craig Dawson', 8012, 'Dawson C.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Daniel Bachmann', 8105, 'Bachmann D.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Danny Welbeck', 3328, 'Welbeck D.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Daryl Janmaat', 8113, 'Janmaat D.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Dimitri Foulquier', 8780, 'Foulquier D.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Étienne Capoue', 8118, 'Capoue E.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Femenía Far', 8125, 'Far F.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Gerard Deulofeu', 8135, 'Deulofeu G.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Heurelho Gomes', 8104, 'Gomes H.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Isaac Success', 11633, 'Success I.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Ismaïla Sarr', 3638, 'Sarr I.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('José Holebas', 8109, 'Holebas J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Marvin Zeegelaar', 8127, 'Zeegelar M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Nathaniel Chalobah', 8126, 'Chalobah N.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Pontus Dahlberg', 31025, 'Dahlberg P.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Quina', 8213, 'Quina, 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Quique Sánchez Flores', 56946, 'Flores Q.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Roberto Pereyra', 8120, 'Pereyra R.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Sebastian Prödl', 8108, 'Prodl S.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Tom Cleverley', 8122, 'Cleverley T.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Tom Dele-Bashiru', 7890, 'Dele-Bashiru A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Troy Deeney', 8130, 'Deeney T.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Will Hughes', 8124, 'Hughes W.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Andros Townsend', 8157, 'Townsend A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Cheikhou Kouyaté', 3618, 'Kouyate C.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Christian Benteke', 8164, 'Benteke C.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Connor Wickham', 8163, 'Wickham C.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Dion Curtis-Henry', 8138, 'Henry D.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Gary Cahill', 7804, 'Cahill G.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Jaïro Riedewald', 8147, 'Riedewald J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('James McArthur', 8152, 'McArthur J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('James McCarthy', 7835, 'McCarthy J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('James Tomkins', 8144, 'Tomkins J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Jason Lokilo', 8165, 'Lokilo J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Jeffrey Schlupp', 8145, 'Schlupp J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Joel Ward', 8141, 'Ward J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Jordan Ayew', 7984, 'Ayew J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Luka Milivojevi?', 3439, 'Milivojevic L.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Mamadou Sakho', 8149, 'Sakho M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Martin Kelly', 8143, 'Kelly M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Max Meyer', 6500, 'Meyer N.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Nikola Tavares', 118494, 'Tavares N.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Nya Kirby', 8161, 'Kirby N.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Patrick van Aanholt', 8146, 'van Aanholt P.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Roy Hodgson', 11628, 'Hodgson R.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Sam Woods', 82153, 'Woods S.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Scott Dann', 8142, 'Dann S.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Stephen Henderson', 4908, 'Henderson S.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Vicente Guaita', 3121, 'Guaita V.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Víctor Camarasa', 33040, 'Camarasa V.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Wayne Hennessey', 8137, 'Hennessey W.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Wilfried Zaha', 8162, 'Zaha W.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Ben Osborn', 11296, 'Osborn B.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Billy Sharp', 4320, 'Sharp B.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Callum Robinson', 11357, 'Robinson C.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Chris Basham', 4295, 'Basham C.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Chris Wilder', 11338, 'Wilder C.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('David McGoldrick', 4247, 'McGoldrick D.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Dean Henderson', 5457, 'Henderson D.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Enda Stevens', 4302, 'Stevens E.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('George Baldock', 4313, 'Baldock G.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Jack O'Connell', 4297, 'O'Connell J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('John Egan', 4425, 'Egan J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('John Fleck', 4307, 'Fleck J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('John Lundstram', 4315, 'Lundstram J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Kean Bryan', 5364, 'Bryan K.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Kieron Freeman', 4296, 'Freeman K.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Leon Clarke', 4322, 'Clarke L.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Luke Freeman', 4035, 'Freeman L.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Lys Mous', 8253, 'Mous L.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Michael Verrips', 9682, 'Verrips M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Muhamed Beši?', 4213, 'Besic M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Oliver McBurnie', 4359, 'McBurnie O.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Oliver Norwood', 3972, 'Norwood O.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Phil Jagielka', 7825, 'Jagielka P.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Ravel Morrison', 38919, 'Morrison R.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Richard Stearman', 4303, 'Stearman R.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Ricky Holmes', 4325, 'Holmes R.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Simon Moore', 4292, 'Moore S.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Aaron Connolly', 8287, 'Connolly A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Aaron Mooy', 3415, 'Mooy A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Adam Webster', 4228, 'Webster A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Alexander Cochrane', 128238, 'Cochrane A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Alireza Jahanbakhsh', 3819, 'Jahanbakhsh A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Archie Davies', 131121, 'Davies A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Bernardo', 9540, 'Bernardo, 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Bojan Radulovic', 58140, 'Radulovic B.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Dale Stephens', 8268, 'Stephens D.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Dan Burn', 4870, 'Burn D.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('David Button', 3954, 'Button D.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Davy Pröpper', 8275, 'Propper D.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Ezequiel Schelotto', 8277, 'Schelotto E.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Florin Andone', 103, 'Andone F.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Gaëtan Bong', 8261, 'Bong G.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Glenn Murray', 8286, 'Murray G.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Graham Potter', 31097, 'Potter G.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Hayden Roberts', 128240, 'Roberts H.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Jack Spong', 131123, 'Spong J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Jason Steele', 4040, 'Steele J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Jordan Davies', 128239, 'Davies J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('José Izquierdo', 3735, 'Izquierdo J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Leandro Trossard', 8984, 'Trossard L.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Leon Balogun', 3380, 'Balogun L.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Lewis Dunk', 8259, 'Dunk L.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Martín Montoya', 33139, 'Montoya M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Maty Ryan', 3403, 'Ryan M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Neal Maupay', 4443, 'Maupay N.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Pascal Groß', 8273, 'Gross P.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Peter Gwargis', 31375, 'Gwargis P.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Romaric Yapi', 125216, 'Yapi R.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Ryan Longman', 131122, 'Longman R.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Shane Duffy', 8265, 'Duffy S.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Solomon March', 8269, 'March S.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Steven Alzate', 56840, 'Alzate S.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Taylor Richards', 102439, 'Richards T.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Teddy Jenks', 131124, 'Jenks T.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Tudor B?lu??', 16005, 'Baluta T.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Warren O'Hora', 131125, 'O'Hora W.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Yves Bissouma', 8410, 'Bissouma Y.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Aaron Cresswell', 8201, 'Cresswell A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Albian Ajeti', 16063, 'Ajeti A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Andrii Yarmolenko', 163, 'Yarmolenko A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Angelo Ogbonna', 8202, 'Ogbonna A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Arthur Masuaku', 8204, 'Masuaka A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Ben Johnson', 8224, 'Johnson B.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Carlos Sánchez', 3729, 'Sanchez C.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Conor Coventry', 92863, 'Conventry C.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('David Martin', 4363, 'Martin D.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Declan Rice', 8215, 'Rice D.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Fabián Balbuena', 1436, 'Balbuena F.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Felipe Anderson', 2060, 'Anderson F.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Gonçalo Cardoso', 82448, 'Cardoso G.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Issa Diop', 8296, 'Diop I.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Jack Wilshere', 3322, 'Wilshere J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('?ukasz Fabia?ski', 3526, 'Fabianski L.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Manuel Lanzini', 3213, 'Lanzini M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Manuel Pellegrini', 11630, 'Pellegrini M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Mark Noble', 8209, 'Noble M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Michail Antonio', 8212, 'Antonio M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Nathan Holland', 8221, 'Holland N.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Pablo Fornals', 33117, 'Fornals P.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Pablo Zabaleta', 8205, 'Zabaleta P.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Robert Snodgrass', 3908, 'Snodgrass R.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Roberto Jiménez', 32793, 'Jimenez R.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Ryan Fredericks', 3966, 'Fredericks R.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Sébastien Haller', 6721, 'Haller S.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Winston Reid', 8200, 'Reid W.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Aaron Ramsdale', 5530, 'Ramsdale A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Adam Smith', 8231, 'Smith A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Andrew Surman', 8246, 'Surman A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Arnaut Danjuma', 9870, 'Danjuma A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Artur Boruc', 8227, 'Boruc A.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Brennan Camp', 102843, 'Camp B.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Callum Wilson', 8251, 'Wilson C.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Charlie Daniels', 8233, 'Daniels C.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Chris Mepham', 4427, 'Mepham C.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Corey Jordan', 8238, 'Jordan C.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Dan Gosling', 8243, 'Gosling D.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('David Brooks', 4321, 'Brooks D.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Diego Rico', 277, 'Rico D.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Dominic Solanke', 7878, 'Solanke D.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Eddie Howe', 11594, 'Howe E.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Gavin Kilkenny', 128312, 'Kilkenny G.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Harry Wilson', 11777, 'Wilson H.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Jack Simpson', 8236, 'Simpson J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Jack Stacey', 5620, 'Stacey J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Jefferson Lerma', 3737, 'Lerma J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Jordon Ibe', 8254, 'Ibe J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Joshua King', 8252, 'King J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Junior Stanislas', 8242, 'Stanislas J.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Lewis Cook', 3327, 'Cook L.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Lloyd Kelly', 4393, 'Kelly L.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Mark Travers', 82135, 'Travers M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Mihai Dobre', 5039, 'Dobre M.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Nathan Aké', 8240, 'Ake N.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Philip Billing', 8184, 'Billing P.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Ryan Fraser', 8247, 'Fraser R.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Simon Francis', 8232, 'Francis S.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Steve Cook', 8234, 'Cook S.', 0, 0)");
            //Sql("INSERT INTO dbo.PlayerStats  (Name, PlayerId, ApiName, Goals, OwnGoals) Values ('Will Dennis', 131127, 'Dennis W.', 0, 0)");

        }

        public override void Down()
        {
        }
    }
}
